name: Build 

on:
  push:
    branches: [ dev26, main ]
  pull_request:
    branches: [ dev26, main ]
  workflow_dispatch: 

env:
  PICO_SDK_PATH: /home/runner/pico-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PSLab Mini Firmware
        uses: actions/checkout@v7

      - name: Install Toolchain
        run: |
          sudo apt update
          sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential python3

      - name: Setup Pico SDK 2.1.0
        run: |
          git clone --depth 1 --branch 2.1.0 https://github.com/raspberrypi/pico-sdk.git $PICO_SDK_PATH
          cd $PICO_SDK_PATH
          git submodule update --init

      - name: Build Firmware for Pico 2 W
        run: |
          mkdir build
          cd build
          cmake .. -DPICO_BOARD=pico2_w -DPICO_SDK_PATH=$PICO_SDK_PATH
          make -j4

      - name: Upload .uf2 Artifact
        uses: actions/upload-artifact@v7
        with:
          name: pslab_pico2_w_firmware
          path: build/*.uf2 
          if-no-files-found: error
